---
- name: Create encrypted file of password
  hosts: all
  gather_facts: false
  vars:
    password_location: "C:\\Temp\\Credential.enc"
      
  tasks:

    - name: Copy file from playbook
      win_copy:
        src: CreateEncryptedFile.ps1
        dest: c:\Temp\CreatedEncryptedFile.ps1

    #- name: Run command
    #  win_shell: >
    #    powershell.exe
    #    -File "C:\Temp\CreatedEncryptedFile.ps1"
    #    -Password "{{ storage_password }}"
    #    -SaveLocation "{{ password_location }}"
        
    - name: Create scheduled task
      win_scheduled_task:
        name: "Create Encrypted File"
        description: "Scheduled task created by Ansible"
        actions:
        - path: powershell.exe
          arguments: >
            -File "C:\Temp\CreatedEncryptedFile.ps1"
            -Password "{{ storage_password }}"
            -SaveLocation "{{ password_location }}"
        #- path: powershell.exe
        #  arguments: >
        #    Unregister-ScheduledTask
        #    -TaskName "Create Encrypted File"
        #    -Confirm:$false  
        state: present
        enabled: yes
        triggers:
        - type: registration
        frequency: once
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        logon_type: password
        #hidden: yes
      #no_log: True

    - name: Delete scheduled task
      win_shell: >
        powershell.exe
        Unregister-ScheduledTask -TaskName "Create Encrypted File" -Confirm:$false
