---
# -------------------------------------------------------#
#   Create encrypted file of password
#
# This will create encrypted password file for the archive
# upload script.
# -------------------------------------------------------#
- name: Create encrypted file of password
  hosts: all
  gather_facts: false
  vars:
    kyndryl_folder: 'C:\Kyndryl\'                   # Temp location to run script from
    password_file: 'Credential.enc'                 # File to store encrypted password in
    script_name: 'CreatedEncryptedFile.ps1'         # Powershell script to create encrypted file
    storage_password: 'Training1!'                  # Password string to convert

  tasks:
    # Check for the Temp folder to store scripts into exist
    - name: Kyndryl folder check
      win_stat:
        path: "{{ kyndryl_folder }}"
      register: folder_check

    # Create temp folder if it does not exist
    - name: Create directory structure if it does not exist
      win_file:
        path: "{{ kyndryl_folder }}"
        state: directory
      when: folder_check.stat.exists == false
        
    # Copy powershell script to temp folder on server
    - name: Copy file from playbook
      win_copy:
        src: "./{{ script_name }}"
        dest: "{{ kyndryl_folder }}{{ script_name }}"

    # Create a windows task schedule to create the encrypted file     
    - name: Create scheduled task to create encrypted file
      win_scheduled_task:
        name: "Create Encrypted File"
        description: "Scheduled task created by Ansible"
        actions:
        - path: powershell.exe
          arguments: >
            -File "{{ kyndryl_folder }}{{ script_name }}"
            -PassString "{{ storage_password }}"
            -SaveLocation "{{ kyndryl_folder }}{{ password_file }}" 
        state: present
        enabled: yes
        triggers:
        - type: registration
        frequency: once
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        logon_type: password
      no_log: True

    # Remove Powershell file 
    - name: Remove Powershell file
      win_file:
        path: "{{ kyndryl_folder }}{{ script_name }}"
        state: absent

    # Remove the Task schedule        
    - name: Remove scheduled task
      win_scheduled_task:
        name: Copy archived logs to server
        state: absent