---
- name: Create encrypted file of password
  hosts: all
  gather_facts: false
  vars:
    password_location: "C:\\Temp\\Credential.enc"
      
  tasks:

    - name: Copy file from playbook
      win_copy:
        src: CreateEncryptedFile.ps1
        dest: c:\Temp\CreatedEncryptedFile.ps1

    #- name: Run command
    #  win_shell: C:\Temp\CreatedEncryptedFile.ps1 -Password "{{ storage_password }}" -SaveLocation "{{ password_location }}"

    - name: Create scheduled task
      win_scheduled_task:
        name: Copy archived logs to server
        description: "Scheduled task created by Ansible"
        actions:
        - path: powershell.exe
          arguments: >
            -File "C:\Temp\CreatedEncryptedFile.ps1"
            -Password "{{ storage_password }}"
            -SaveLocation "{{ password_location }}"
        state: present
        enabled: yes
        triggers:
        - type: registration
          repetition:
            interval: PT1M
            #duration: PT5M
            stop_at_duration_end: yes
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        logon_type: password
        hidden: yes
      #no_log: True
