---
- name: Create encrypted file of password
  hosts: all
  gather_facts: false
  vars:
    password_location: "C:\\Temp\\Credential.enc"
      
  tasks:

    - name: Copy file from playbook
      win_copy:
        src: CreatedEncryptedFile.ps1
        dest: c:\Temp\CreatedEncryptedFile.ps1

    - name: Run command
      win_shell: C:\Temp\CreatedEncryptedFile.ps1 -Password {{ storage_password }} -SaveLocation {{ password_location }}
