---
# -------------------------------------------------------#
#   Delete related upload files and schedule 
#
# This will remove 
# -------------------------------------------------------#
- name: Delete scheduled task to copy archive files
  hosts: all
  gather_facts: false
  vars:
    kyndryl_folder: 'C:\Kyndryl\'
    password_file: 'Credential.enc' 
    upload_file: 'UploadArchive.ps1'

  tasks:
    # Remove task schedule        
    - name: Delete scheduled task
      win_scheduled_task:
        name: "Copy archived logs to server"
        state: absent

    # Remove task schedule        
    - name: Delete scheduled task
      win_scheduled_task:
        name: "Create Encrypted File"
        state: absent

    # Remove Powershell file 
    - name: Remove Powershell file
      win_file:
        path: "{{ kyndryl_folder }}{{ password_file }}"
        state: absent
    
    # Remove Powershell file 
    - name: Remove Powershell file
      win_file:
        path: "{{ kyndryl_folder }}{{ upload_file }}"
        state: absent  