---
- name: Create scheduled task to copy files
  hosts: all
   
  tasks:
    
    - name: Get scheduled task info
      win_shell: Get-ScheduledTaskInfo -TaskName "\Copy archived logs to server" | ConvertTo-Json
      register: task_info
    
    # Test debug command 
    - name: "Debug output"
      debug: 
        msg: "{{ task_info }}"

    - name: Convert Information
      set_fact:
        task_Dict: "{{ task_info | from_json }}"
        var_date_now: "{{ ansible_date_time.iso8601 }}"
   
#    - name: Write task info to file
#      copy:
#        content: |
#          <tr>
#            <td>{{ ansible_hostname }}</td>
#            <td>{{ task_info.LastRunTime }}</td>
#            <td>{{ task_info.LastTaskResult }}</td>
#          </tr>
#        dest: "{ansible_hostname}_Report.htmlsegment"  
#      delegate_to: localhost
#
#    - name: Inserted provided delimiter in between each fragment
#      assemble:
#        src: /
#        dest: /LogReport.html
#        #delimiter: '### START FRAGMENT ###'
#      regex: .*htmlsegment
#      run_once: true
#      delegate_to: localhost
#
#    - name: Read template and 
#      set_fact:
#        summary_results:  "{{ lookup('file', './LogReport.html') }}"
#        summart_:  "{{ lookup('template', './Template.html') }}"

      
