---
- name: Create scheduled task to copy files
  hosts: all
   
  tasks:
    # | ConvertTo-Json
    #- name: Get scheduled task info
    #  win_shell: Get-ScheduledTaskInfo -TaskName "\Copy archived logs to server" 
    #  register: task_info
    
    - name: Get information about a task in the root folder
      win_scheduled_task_stat:
        name: "Copy archived logs to server"
      register: taskStat

    # Test debug command 
    - name: "Debug output"
      debug:
        msg: "{{ taskStat.state.last_run_time }}  | {{ taskStat.state.last_task_result }}"

    - name: Write task info to file
      copy:
        content: |
          <tr>
            <td>{{ ansible_hostname }}</td>
            <td>{{ taskStat.state.last_run_time }}</td>
            <td>{{ taskStat.state.last_task_result }}</td>
          </tr>
        dest: "{ansible_hostname}_Report.htmlsegment"  
      delegate_to: localhost
#
#    - name: Inserted provided delimiter in between each fragment
#      assemble:
#        src: /
#        dest: /LogReport.html
#        #delimiter: '### START FRAGMENT ###'
#      regex: .*htmlsegment
#      run_once: true
#      delegate_to: localhost
#
#    - name: Read template and 
#      set_fact:
#        summary_results:  "{{ lookup('file', './LogReport.html') }}"
#        summart_:  "{{ lookup('template', './Template.html') }}"

      
