---
# -------------------------------------------------------#
#   Excution Report 
#
# This will produce a report on the event log archive 
# upload schedule tasks.
# -------------------------------------------------------#
- name: Create a report of event log archive schedule tasks
  hosts: all
  
  tasks:
    
    - name: Get information about a task in the root folder
      win_scheduled_task_stat:
        name: "Copy archived logs to server"
      register: taskStat
  
    - name: Write task info to file
      copy:
        content: "<tr><td>{{ ansible_hostname }}</td><td>{{ taskStat.state.last_run_time }}</td><td>{{ taskStat.state.last_task_result }}</td></tr>"
        dest: "{{ansible_hostname}}_Report.htmlsegment"  
      delegate_to: localhost

    - name: Combine htmlsegment files
      assemble:
        src: "./"
        dest: LogReport.html
        regexp: .*_Report.htmlsegment
      run_once: true
      delegate_to: localhost 

    - name: Set variables for email body template 
      set_fact:
        var_date_now: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
        overall_status: "Good"
        schedul_data: "{{ lookup('file', 'LogReport.html') }}"        
      run_once: true
      delegate_to: localhost
      
    # Read template and combine with the variables before
    - name: Read template and combine with the variables before
      set_fact:
        email_body: "{{ lookup('template', 'templates/EmailBodyHTML.j2') }}"
      run_once: true
      delegate_to: localhost
      
    # Write file to server
    - name:
      copy:
        content: "{{ email_body }}"
        dest: "EmailBody_{{ var_date_now }}.html"
      delegate_to: localhost
      run_once: true

    - name: "Read a file content"
      shell: "cat EmailBody_{{ var_date_now }}.html"
      register: file_content
      delegate_to: localhost

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"

    # Email report
#    - name: Email information
#      mail:
#        host: ????????
#        port: 25
#        to: "{{ destination_email }}"
#        from: ansible@kyndryl.com
#        subject: "Event Log Archive Report - {{ file_Summary }}"
#        body: "Server status - {{ file_Summary }}"
#        attach: "/tmp/MyTest/Citrix_Status_{{ var_date_now }}.html"
#      delegate_to: localhost
#      run_once: true

      
