---
# -------------------------------------------------------#
#   Excution Report 
#
# This will produce a report on the event log archive 
# upload schedule tasks.
# -------------------------------------------------------#
- name: Create a report of event log archive schedule tasks
  hosts: all
  vars: 
      destination_email: ""
  
  tasks:
    

    - name: Get information about a task in the root folder
      win_scheduled_task_stat:
        name: "Copy archived logs to server"
      register: taskStat
    
    - name: Set overall status if good 
      set_fact:
        overall_status: "Good"
      run_once: true
      delegate_to: localhost
      when: taskStat.state.last_task_result == 0 

    - name: Set overall status if bad
      set_fact:
        overall_status: "Bad"
      run_once: true
      delegate_to: localhost
      when: taskStat.state.last_task_result != 0 

    - name: Write task info to file
      copy:
        content: "<tr class='goodData'><td>{{ ansible_hostname }}</td><td>{{ taskStat.state.last_run_time }}</td><td>{{ taskStat.state.last_task_result }}</td></tr>"
        dest: "{{ansible_hostname}}_Report.htmlsegment"  
      delegate_to: localhost
      when: taskStat.state.last_task_result == 0 

    - name: Write task info to file
      copy:
        content: "<tr class='badData'><td>{{ ansible_hostname }}</td><td>{{ taskStat.state.last_run_time }}</td><td>{{ taskStat.state.last_task_result }}</td></tr>"
        dest: "{{ansible_hostname}}_Report.htmlsegment"  
      delegate_to: localhost
      when: taskStat.state.last_task_result != 0 

    - name: Combine htmlsegment files
      assemble:
        src: "./"
        dest: LogReport.html
        regexp: .*_Report.htmlsegment
      run_once: true
      delegate_to: localhost 

    - name: Set variables for email body template 
      set_fact:
        var_date_now: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
        overall_status: "Good"
        schedul_data: "{{ lookup('file', 'LogReport.html') }}"        
      run_once: true
      delegate_to: localhost
      
    # Read template and combine with the variables before
    - name: Read template and combine with the variables before
      set_fact:
        email_body: "{{ lookup('template', 'templates/EmailBodyHTML.j2') }}"
      run_once: true
      delegate_to: localhost
      
    # Debug write out 
    - name: "Print the file content to a console"
      debug:
        msg: "{{ email_body }}"
      run_once: true
      delegate_to: localhost
    # Email report
#    - name: Email information
#      mail:
#        host: ????????
#        port: 25
#        to: "{{ destination_email }}"
#        from: ansible@kyndryl.com
#        subject: "Event Log Archive Report - {{ var_date_now }}"
#        body: "{{ email_body }}"
#      delegate_to: localhost
#      run_once: true