---
- name: Create scheduled task to copy files
  hosts: all
   
  tasks:
    
    - name: Get scheduled task info
      win_shell: Get-ScheduledTaskInfo -TaskName "<NAME OF TASK>" | ConvertTo-Json
      register: task_info

    - name: Convert Information
      set_fact:
        task_info: "{{ task_info | from_json }}"
        var_date_now: "{{ ansible_date_time.iso8601 }}"
    
    - name: Write task info to file
      copy:
        content: |
          <tr>
            <td>{{ ansible_hostname }}</td>
            <td>{{ task_info.LastRunTime }}</td>
            <td>{{ task_info.LastTaskResult }}</td>
          </tr>
        dest: "{ansible_hostname}_Report.html"  
      delegate_to: localhost

    - name: Read template
      set_fact:
        file_StoreFront:  "{{ lookup('file', './Template.html') }}"

      
