---
- name: Create scheduled task to copy files
  hosts: all
   
  tasks:
    
    - name: Get scheduled task info
      win_shell: Get-ScheduledTaskInfo -TaskName "<NAME OF TASK>" | ConvertTo-Json
      register: task_info
      
    - name: Create copy of single file
      copy:
        content : "{{ your_json_feed }}"
        dest: "{ansible_hostname}_Report.html"   
